#!/usr/bin/env bash
## Author: EarthlySkies
## License: MIT
## A Bubblewrap profile for the "arch-audit" utility
## Target program: https://github.com/ilpianista/arch-audit

## Internal variables for the sandbox
BOXUID="95512"
BOXUSER="audit"
BOXHOME="/home/$BOXUSER"

/usr/bin/bwrap \
  --symlink usr/bin /bin \
  --symlink usr/lib /lib \
  --symlink usr/lib /lib64 \
  --symlink usr/bin /sbin \
  --dev /dev \
  --ro-bind-try /etc/arch-audit /etc/arch-audit \
  --ro-bind-try /etc/ca-certificates /etc/ca-certificates \
  --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
  --ro-bind-try /etc/ssl /etc/ssl \
  --ro-bind-try /usr/bin/arch-audit /usr/bin/arch-audit \
  --ro-bind-try /usr/lib/ /usr/lib \
  --symlink /usr/lib /usr/lib64 \
  --ro-bind-try /usr/share/terminfo /usr/share/terminfo \
  --ro-bind-try /var/lib/pacman /var/lib/pacman \
  --remount-ro / \
  --unshare-all \
  --share-net \
  --uid "$BOXUID" \
  --gid "$BOXUID" \
  --hostname "$BOXUSER"-sandbox \
  --clearenv \
  --setenv HOME "$BOXHOME" \
  --setenv LD_PRELOAD "/usr/lib/libhardened_malloc.so" \
  --setenv LOGNAME "$BOXUSER" \
  --setenv TERM "$TERM" \
  --setenv PATH "/usr/bin" \
  --setenv UID "$BOXUID" \
  --setenv USER "$BOXUSER" \
  --cap-drop ALL \
  --die-with-parent \
  --new-session \
  /usr/bin/arch-audit "$@"
